male_names = [
    'Alexandre', 'Eduardo', 'Henrique', 'Murilo', 'Theo', 'André', 'Enrico', 'Henry', 'Nathan', 'Thiago',
    'Antônio', 'Enzo', 'Ian', 'Otávio', 'Thomas', 'Augusto', 'Erick', 'Isaac', 'Pietro', 'Vicente',
    'Breno', 'Felipe', 'João', 'Rafael', 'Vinícius', 'Bruno', 'Fernando', 'Kaique', 'Raul', 'Vitor',
    'Caio', 'Francisco', 'Leonardo', 'Rian', 'Yago', 'Cauã', 'Frederico', 'Luan', 'Ricardo', 'Ygor',
    'Daniel', 'Guilherme', 'Lucas', 'Rodrigo', 'Yuri', 'Danilo', 'Gustavo', 'Mathias', 'Samuel'
]

female_names = [
    'Agatha',  'Camila', 'Esther', 'Isis', 'Maitê', 'Natália', 'Alícia', 'Carolina', 'Fernanda', 'Joana',
    'Malu', 'Nicole', 'Amanda', 'Catarina', 'Gabriela', 'Laís', 'Maria', 'Olívia', 'Ana Cecília', 'Gabrielle',
    'Lara', 'Mariah', 'Pietra', 'Antonela', 'Clara', 'Giovanna', 'Larissa', 'Mariana', 'Rafaela', 'Aurora',
    'Clarice', 'Giulia', 'Lavínia', 'Marina', 'Rebeca', 'Bárbara', 'Eduarda', 'Heloísa', 'Letícia', 'Maya', 'Sara',
    'Beatriz', 'Elisa', 'Isabel', 'Liz', 'Melissa', 'Sophie', 'Bianca', 'Emanuelly', 'Isabelly', 'Lorena',
    'Milena', 'Stella', 'Bruna', 'Emilly', 'Isadora', 'Luana', 'Mirella', 'Vitória', 'Yasmin'
]

last_names = [
     'Silva', 'Souza', 'Costa', 'Santos', 'Oliveira', 'Pereira', 'Rodrigues', 'Almeida', 'Nascimento',
     'Lima', 'Araújo', 'Fernandes', 'Carvalho', 'Gomes', 'Martins', 'Rocha', 'Ribeiro', 'Alves',
     'Monteiro', 'Mendes', 'Barros', 'Freitas', 'Barbosa', 'Pinto', 'Moura', 'Cavalcanti',
     'Dias', 'Castro', 'Campos', 'Cardoso'
]

street_names = [
    'Rua Germano Vítor dos Santos',
    'Rua Glucínio',
    'Rua Nelson Ferreira',
    'Rua Clodomiro Pinheiro',
    'Rua Emílio Retrosi',
    'Praça Antônio Pereira Martins',
    'Rua Comendador Assad Abdalla',
    'Rua Ouro Verde',
    'Rua Casa da Boavista',
    'Rua John Redford',
    'Avenida Nazaré',
    'Avenida Adelino Jorge Montenegro',
    'Rua Rynaldo Borgianni',
    'Rua Arvore da Cera',
    'Rua Acioli Monteiro',
    'Rua Manuel Teles Vitancos',
    'Rua Antônio Mariani',
    'Rua Tiburno',
    'Rua Venceslau José Bernardes',
    'Avenida João Barreto de Menezes',
    'Praça João Paulo Meira',
    'Rua Rubens Mascarenhas',
    'Viela Eurides da Silva Carvalho',
    'Travessa Quatro de Setembro',
    'Rua Soldado José Reymão',
    'Rua Cravo do Campo',
    'Travessa Tres Pingos Dagua',
    'Rua Itacaranha',
    'Rua Hercí­lio Luz',
    'Rua Xororó',
    'Praça Monteiro Lobato',
    'Rua Galatea',
    'Praça Madre Maria Josefina Villac',
    'Rua Banana-Branca',
    'Rua Dominique Lagru',
    'Rua Nova Olinda do Norte',
    'Rua Paolo Porpora',
    'Travessa Bom Jesus do Norte',
    'Rua Paulo Bastide',
    'Viaduto Guadalajara',
    'Rua Padre Ângelo Gioielli',
    'Rua Angélicas',
    'Rua Belfort Roxo',
    'Rua Otací­lio Gomes',
    'Rua Alto Santa Maria',
    'Rua Valdomiro Urbani',
    'Travessa Jaime Eustáquio Pacheco',
    'Rua Chaguaramas',
    'Rua David Fabricius',
    'Rua Doutor Americano',
    'Via de Pedestre Cerebia',
    'Rua Durval de Almeida Santana',
    'Rua Hemisfério',
    'Rua João da Silva Moraes',
    'Travessa do Fado',
    'Rua Cesare Badiali',
    'Rua Jales Rodrigues Silva',
    'Rua Henrique Jorge Guedes',
    'Rua Charles Naufal',
    'Rua Sinfonia Escocesa',
    'Avenida Wando Henrique Cardim',
    'Rua Oscarina Maria de Jesus',
    'Rua Margaridas Amarelas',
    'Via Marãni',
    'Rua Crispo',
    'Rua Júlio Ribeiro Neto',
    'Rua Guilherme Studart',
    'Travessa Ângelo Berardi',
    'Praça Benjamim',
    'Rua Francisco Cordeiro Lavaredas',
    'Rua Luís Morales',
    'Praça Ocupação',
    'Rua da Independência',
    'Rua Rosária Ana Barbosa',
    'Travessa Rio Tarauacá',
    'Rua José Branco',
    'Rua Virgí­lio Manente',
    'Rua Sardoá',
    'Avenida Carini',
    'Rua Sargento Benevides Valente Montes',
    'Rua Frauenfeld',
    'Rua Carlos Reis',
    'Rua Marques Ribeiro',
    'Rua Henrique Gomes de Brito',
    'Rua Tomás de Santa Maria',
    'Praça Amélia Terezinha',
    'Rua Lua',
    'Rua Linda Lucotti',
    'Rua Maria Auxiliadora',
    'Rua Doutor Ibsen da Costa Manso',
    'Avenida Doutor Mário Vilas Boas Rodrigues'','
    'Rua Anael',
    'Praça Virgí­lio Lúcio',
    'Travessa Fantasia Cromática',
    'Rua Verão Vermelho',
    'Rua César Aretusi',
    'Rua Ribeirão Pires',
    'Rua Alvaro Martins Sevilha',
    'Praça Estrela do Norte',
    'Rua Alexandre Davidenko',
    'Rua Caçador Narciso',
    'Rua Manilha',
    'Estrada da Biacica',
    'Rua Beira Rio Particular',
    'Rua Cascavel',
    'Rua Ismael da Silva Júnior',
    'Rua Doutor Sebastião de Lima',
    'Rua Marcelo Bernardini',
    'Rua Sargento Iguatemi Azevedo',
    'Rua Padre Herreiro',
    'Rua José Matias de Araújo',
    'Praça João Bosco Penido Burnier',
    'Rua Guiné',
    'Rua Solidês',
    'Rua Antonio Jose Parra Primeiro',
    'Rua Paulo Adorno',
    'Rua Reinaldo Pereira',
    'Rua Mestre',
    'Praça Monsenhor Escrivá',
    'Rua Brás Cardoso',
    'Rua Chacorore',
    'Avenida Vinte e Quatro de Fevereiro',
    'Rua Teixeira e Sousa',
    'Rua Aldo Manucio',
    'Praça Kant',
    'Rua Justino Rodrigues da Conceição',
    'Rua João Cariani',
    'Avenida Águia de Haia',
    'Beco das Flores',
    'Travessa Valongo',
    'Rua Carvalho de Freitas',
    'Rua Renato Pereira',
    'Rua Natalina Roque Estefani',
    'Rua Hiran Pinto da Silva',
    'Rua Sargento Feliz Marqueti',
    'Rua Belchior de Melo',
    'Rua Heliodoro de Paiva',
    'Rua Cinco de Outubro',
    'Travessa Luí­s Ellmerich',
    'Rua Olavo Leite',
    'Rua George Raiger',
    'Rua Olímpio Brás de Sousa',
    'Praça Bauxita',
    'Rua Iná',
    'Rua Professora Aparecida Relvas',
    'Rua Hermilo Alves',
    'Rua Real Grandeza',
    'Rua Sitiantes',
    'Rua Margarida Zingg',
    'Rua Pirai do Norte',
    'Travessa Benvenuto Coronaro',
    'Travessa Serra do Imeri',
    'Rua Raimundo da Silva',
    'Estrada Serraria',
    'Rua Eutrópio Wilhem de Freitas',
    'Rua Madalena',
    'Rua Marquês de Cascais',
    'Rua Hera Terrestre',
    'Rua Jacó Bertillon',
    'Travessa Maria Leneru',
    'Avenida Baltazar Santana',
    'Rua Nara Leão',
    'Rua Carla',
    'Rua Doutor Raul da Rocha Medeiro',
    'Rua Laura Vicuna',
    'Rua Xavier da Veiga',
    'Travessa Cruz das Almas',
    'Travessa Igarapé Vintém',
    'Rua João Batista Duarte',
    'Rua Kleber Afonso',
    'Rua de Castro Laboreiro',
    'Rua Nova Friburgo',
    'Rua Madalena Madureira',
    'Rua das Promessas',
    'Rua Tatini',
    'Travessa Engenheiro Cestari',
    'Praça Garcia',
    'Rua Celso de Almeida Sena',
    'Travessa Amaro da Silva',
    'Rua Carimbó',
    'Rua Carlo Dolci',
    'Rua Nabor de Morais',
    'Praça Bartolomeo Manfredi',
    'Rua Glycério Almeida Maciel',
    'Rua Nova Belém',
    'Rua Doutor Ubaldino do Amaral',
    'Rua José Martorano Sobrinho',
    'Rua André Luiz',
    'Rua Bento Gurgel de Salles',
    'Rua Janauira',
    'Rua Ibaretama',
    'Rua Palmira Santa Edwirges',
    'Rua Walter Carlson',
    'Rua Ruy Coelho',
    'Praça dos Artesãos Calabreses',
    'Rua Luí­s Gonzaga de Almeida',
    'Estrada Perus',
    'Rua Municipios',
    'Rua João Faustino',
    'Rua Boieiros',
]

category = [
    "Automotive and Transport", "Business and Finance", "Chemicals and Materials", "Company Reports",
    "Consumer Goods and Services", "Country Reports",  "Energy and Natural Resources",
    "Food and Beverage", "Government and Public Sector", "Healthcare", "Humanities Books",
    "Industry Standards", "Manufacturing and Construction",  "Military Aerospace and Defense",
    "Pharmaceuticals",  "Science Books", "Telecommunications and Computing"
]

products = [
    'Smart devices', 'Portable speakers', 'Back cases', 'Cables and cords for computers',
    'Power banks and chargers', 'Headphones', 'Bluetooth devices', 'Memory cards',
    'USB devices', 'Printers', 'Screen guards'
]

citys = [
    'São Paulo',
    'Rio de Janeiro',
    'Salvador',
    'Brasília',
    'Fortaleza',
    'Belo Horizonte',
    'Manaus',
    'Curitiba',
    'Recife',
    'Porto Alegre',
    'Belém',
    'Goiânia',
    'Guarulhos',
    'Campinas',
    'São Luís',
    'São Gonçalo',
    'Maceió',
    'Duque de Caxias',
    'Teresina',
    'Natal',
]
